### ISSUE TITLE
Latest version of PhpStorm #PS-242.20224.361 is not supported

### ISSUE THREAD

**Issue by frankvanhest** [dev-cycles/contextive#81]
**Describe the bug**
The latest version of PhpStorm #PS-242.20224.361 is not supported by this plugin and the IDE has disabled the plugin for now.
I'm properly too soon by submitting this. I hope a new version is coming, so I can use the plugin again in the latest version of PhpStorm. Thank you for this great plugin.

**Screenshots**
<img width="455" alt="Screenshot 2024-08-21 at 08 45 26" src="https://github.com/user-attachments/assets/cf3f467c-5dfb-4eb7-98fd-4c0f954e164c">

**Desktop (please complete the following information):**
 - macOS 14.5

**Comment by chrissimon-au** [comment]
Thanks for the heads up and kind words :) New version coming soon!

**Comment by chrissimon-au** [comment]
Fixed in 08308bff2056fd1af764d88649de7fe90b8516b1

**Comment by chrissimon-au** [comment]
Now approved in the plugin store here: https://plugins.jetbrains.com/plugin/23928-contextive/versions/stable/598421

@frankvanhest let me know if any problems

**Comment by frankvanhest** [comment]
@chrissimon-au, thank you for the new release!
